service: test-application
provider:
    name: aws
    runtime: nodejs16.x
    stage: dev
    region: us-east-1
    memorySize: 1024

functions:
    app:
        handler: app/app.handler
        events:
            - http:
                  path: /
                  method: GET
                  cors: true
            - http:
                  path: /api/hello
                  method: GET
                  cors: true
            - http:
                  path: /api/createtodo
                  method: POST
                  cors: true
            - http:
                  path: /api/gettodos
                  method: GET
                  cors: true
            - http:
                  path: /api/getsingletodo
                  method: GET
                  cors: true
            - http:
                  path: /api/updatetodo
                  method: PUT
                  cors: true
            - http:
                  path: /api/deletesingletodo
                  method: DELETE
                  cors: true
            - http:
                  path: /api/deleteallcompletedtodos
                  method: DELETE
                  cors: true
            - http:
                  path: /api/deletealltodos
                  method: DELETE
                  cors: true
