service: test-application
provider:
  name: aws
  runtime: nodejs16.x
  stage: dev
  region: us-east-1
  memorySize: 1024

functions:
  app:
    handler: app/app.handler
    events:
      - http:
          path: /
          method: GET
          cors: true
      - http:
          path: /api/hello
          method: GET
          cors: true
      - http:
          path: /api/createtodo
          method: POST
          cors: true
